image: tourguide
services:
  - docker:tourguide

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: j.de-la-osa
  APP_NAME: tourguide
  REPO: p8-jd

stages:
  - build
  - test
  - docker
  - docker-stop

gradle-build:
  image: openjdk:8
  stage: build
  script: "gradlew clean build"
  artifacts:
    paths:
      - target/*.jar

gradle-test:
  image: openjdk:8
  stage: test
  script: "gradlew test"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - docker build --build-arg JAR_FILE="build/libs/*.jar" -t tourguide .
    - docker run -p 8085:8085 tourguide

docker-stop:
  stage: docker-stop
  script:
    - docker stop tourguide
